#!/usr/bin/env node
/**
 * Генерирует CSS для иконок тулбара Slidev.
 * Workaround: в UnoCSS 66 + Slidev 52 collectionsNodeResolvePath передаётся массивом,
 * из-за чего preset-icons не подхватывает @iconify/json в dev.
 */
import { writeFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import { createGenerator } from '@unocss/core'
import presetIcons from '@unocss/preset-icons'

const __dirname = dirname(fileURLToPath(import.meta.url))
const outFile = resolve(__dirname, '../../theme/styles/toolbar-icons.css')

const toolbarIcons = [
  'i-carbon:maximize',
  'i-carbon:minimize',
  'i-carbon:arrow-left',
  'i-carbon:arrow-right',
  'i-carbon:apps',
  'i-carbon-moon',
  'i-carbon-sun',
  'i-carbon-magic-wand',
  'i-carbon-magic-wand-filled',
  'i-ph-cursor-fill',
  'i-ph-cursor-duotone',
  'i-carbon:pen',
  'i-carbon:presentation-file',
  'i-carbon:user-speaker',
  'i-carbon:text-annotation-toggle',
  'i-carbon:download',
  'i-carbon:document-pdf',
  'i-carbon:information',
  'i-carbon:template',
  'i-carbon:settings-adjust',
  'i-carbon:user-avatar',
  'i-carbon:video',
  'i-carbon:chevron-up',
  'i-carbon:chevron-down',
  'i-ph:arrow-up-bold',
  'i-ph:arrow-down-bold',
  'i-carbon:document-multiple-01',
  'i-tdesign:animation',
  'i-carbon:open-panel-right',
  'i-carbon:open-panel-bottom',
  'i-carbon:close',
  'i-carbon:add',
  'i-carbon:arrow-up',
  'i-carbon:arrow-down',
  'i-carbon:view',
  'i-carbon:view-off',
  'i-carbon:edit',
  'i-carbon:trash-can',
  'i-carbon:chevron-right',
  'i-carbon:record',
  'i-carbon:stop-filled',
  'i-carbon:pause',
  'i-carbon:play',
]

const uno = await createGenerator({
  presets: [
    presetIcons({
      cdn: 'https://esm.sh/',
      extraProperties: {
        display: 'inline-block',
        'vertical-align': 'middle',
        width: '1.2em',
        height: '1.2em',
      },
    }),
  ],
})

const { css } = await uno.generate(new Set(toolbarIcons), { preflights: false })

writeFileSync(outFile, `/* auto-generated by addon/scripts/generate-toolbar-icons.ts */\n${css}\n`)
console.log(`Wrote ${toolbarIcons.length} toolbar icons → ${outFile}`)
