#!/usr/bin/env node
/**
 * Генерирует CSS для иконок Point (icon="i-…" в слайдах).
 * Локальный @iconify/json — без CDN; :class="icon" не попадает в скан UnoCSS.
 */
import { readdirSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, join, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import { generateIconsCss } from './lib/icons-css.ts'

const __dirname = dirname(fileURLToPath(import.meta.url))
const root = resolve(__dirname, '../..')
const outFile = resolve(root, 'theme/styles/point-icons.css')

const scanDirs = ['parts', 'components']
const scanFiles = ['slides.md']

function collectIcons(): string[] {
  const icons = new Set<string>()
  const re = /icon="(i-[^"]+)"/g

  for (const file of scanFiles) {
    const content = readFileSync(join(root, file), 'utf8')
    for (const match of content.matchAll(re))
      icons.add(match[1])
  }

  for (const dir of scanDirs) {
    const dirPath = join(root, dir)
    for (const name of readdirSync(dirPath, { recursive: true })) {
      if (typeof name !== 'string' || !name.endsWith('.md') && !name.endsWith('.vue'))
        continue
      const content = readFileSync(join(dirPath, name), 'utf8')
      for (const match of content.matchAll(re))
        icons.add(match[1])
    }
  }

  return [...icons].sort()
}

const pointIcons = collectIcons()

if (pointIcons.length === 0) {
  writeFileSync(outFile, '/* auto-generated by addon/scripts/generate-point-icons.ts — no icons found */\n')
  console.log('No point icons found')
  process.exit(0)
}

const css = await generateIconsCss(pointIcons, {
  width: '1em',
  height: '1em',
})

writeFileSync(outFile, `/* auto-generated by addon/scripts/generate-point-icons.ts */\n${css}`)
console.log(`Wrote ${pointIcons.length} point icons → ${outFile}`)
